name: CI
on:
  push:
    paths:
      - "vault-harvester/**"
  pull_request:
    paths:
      - "batch-nft-reveal/**"

jobs:
  test:
    name: Test Vault Harvester
    runs-on: ubuntu-latest
    env:
      REPORT_GAS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Vault Harvester dependencies
        working-directory: ./vault-harvester
        run: yarn install --frozen-lockfile

      - name: Compile Vault Harvester contracts
        working-directory: ./vault-harvester
        run: yarn compile

      - name: Test Vault Harvester contracts
        working-directory: ./vault-harvester
        run: yarn test
